export const TYPE_NUM_TO_STRING: Record<number, string> = {
  5: "FixedText",
  10: "FreeText",
  15: "FreeDraw",
  30: "KeyboardText",
  40: "Date",
  50: "Time",
  55: "TimeCalculate",
  60: "Numeric",
  65: "InputNumeric",
  67: "Calculate",
  70: "Select",
  80: "MultiSelect",
  90: "Check",
  100: "Image",
  110: "NumberHours",
  111: "CalendarDate",
  119: "Handwriting",
  120: "Gps",
  121: "QRCode",
  122: "CodeReader",
  125: "SelectMaster",
  126: "Action",
  131: "AudioRecording",
  132: "Scandit",
  133: "EdgeOCR",
};

export const VALID_CLUSTER_TYPE_NAMES = new Set(Object.values(TYPE_NUM_TO_STRING));
